name: Retry Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build

      - name: Start Momento Local
        run: |
          docker run --cap-add=NET_ADMIN --rm -d -p 8080:8080 -p 9090:9090 -e LOG_LEVEL=debug gomomento/momento-local --enable-test-admin

      - name: Build and test with Momento Local
        env:
          MOMENTO_PORT: 8080
          TEST_ADMIN_PORT: 9090
        run: make test-retries

      - name: Clean up Docker Container
        if: always()
        run: |
          docker rm -f momento-local || true